---
version: '3'
services:
  prometheus:
    image: "prom/prometheus:v2.18.1"
    ports:
      - "9090:9090"
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: "grafana/grafana:6.7.3"
    ports: 
      - "3000:3000"
    volumes:
      - "./conf/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./conf/grafana/dashboards:/etc/grafana/provisioning/dashboards"

  cadvisor:
    image: "gcr.io/google-containers/cadvisor"
    volumes:
      - /:/rootfs:ro 
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
      - /dev/disk/:/dev/disk:ro 
    ports:
      - "9338:8080"
    privileged: true
    devices:
      - "/dev/kmsg"
